// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.2
// source: ports.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmulatorPorts_Read_FullMethodName  = "/emulator_ports.EmulatorPorts/Read"
	EmulatorPorts_Write_FullMethodName = "/emulator_ports.EmulatorPorts/Write"
)

// EmulatorPortsClient is the client API for EmulatorPorts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmulatorPortsClient interface {
	Read(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Answer, error)
	Write(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Answer, error)
}

type emulatorPortsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmulatorPortsClient(cc grpc.ClientConnInterface) EmulatorPortsClient {
	return &emulatorPortsClient{cc}
}

func (c *emulatorPortsClient) Read(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, EmulatorPorts_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorPortsClient) Write(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, EmulatorPorts_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmulatorPortsServer is the server API for EmulatorPorts service.
// All implementations must embed UnimplementedEmulatorPortsServer
// for forward compatibility.
type EmulatorPortsServer interface {
	Read(context.Context, *emptypb.Empty) (*Answer, error)
	Write(context.Context, *emptypb.Empty) (*Answer, error)
	mustEmbedUnimplementedEmulatorPortsServer()
}

// UnimplementedEmulatorPortsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmulatorPortsServer struct{}

func (UnimplementedEmulatorPortsServer) Read(context.Context, *emptypb.Empty) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedEmulatorPortsServer) Write(context.Context, *emptypb.Empty) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedEmulatorPortsServer) mustEmbedUnimplementedEmulatorPortsServer() {}
func (UnimplementedEmulatorPortsServer) testEmbeddedByValue()                       {}

// UnsafeEmulatorPortsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmulatorPortsServer will
// result in compilation errors.
type UnsafeEmulatorPortsServer interface {
	mustEmbedUnimplementedEmulatorPortsServer()
}

func RegisterEmulatorPortsServer(s grpc.ServiceRegistrar, srv EmulatorPortsServer) {
	// If the following call pancis, it indicates UnimplementedEmulatorPortsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmulatorPorts_ServiceDesc, srv)
}

func _EmulatorPorts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorPortsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorPorts_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorPortsServer).Read(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorPorts_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorPortsServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorPorts_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorPortsServer).Write(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmulatorPorts_ServiceDesc is the grpc.ServiceDesc for EmulatorPorts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmulatorPorts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emulator_ports.EmulatorPorts",
	HandlerType: (*EmulatorPortsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _EmulatorPorts_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _EmulatorPorts_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ports.proto",
}
